- name: configuring the YUM repos
  ansible.builtin.shell: "{{item}}"
  loop:
  - "curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash"
  - "curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash"

- name: installing the rabbitmq
  ansible.builtin.yum:
    name: rabbitmq-server
    state: installed


- name: enabling the rabbitmq server
  ansible.builtin.service:
    name: rabbitmq-server
    enabled: yes
    state: started

- name: creating the user for rabbitmq
  ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123

- name: setting the permissions for the user
  ansible.builtin.shell: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"