- name: installing nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: installing_nodejs

- name: creating user and directory
  ansible.builtin.import_role:
    name: common
    tasks_from: creating_user_and_directory

- name: downloading the catalogue files and archiveing
  ansible.builtin.import_role:
    name: common
    tasks_from: downloading_unarchiving

- name: Installing npm dependencies
  community.general.npm:
    name: npm
    path: /app

- name: copying the catalogue.service
  ansible.builtin.copy:
    src: /home/centos/roboshop-ansible/catalogue.service
    dest: /etc/systemd/system/catalogue.service


- name: daemon reload catalogue
  ansible.builtin.systemd:
    daemon_reload: true
    name: catalogue

- name: enabling the catalogue
  ansible.builtin.service:
    name: catalogue
    enabled: yes
    state: restarted

  - name: setting up the mongodb repo file
    ansible.builtin.copy:
      src: /home/centos/roboshop-ansible/mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: installing the mongodbshell
    ansible.builtin.yum:
      name: mongodb-org-shell
      state: installed

  - name: loading the schema
    ansible.builtin.command: mongo --host mongodb.saikiransudhireddy.com < /app/schema/catalogue.js